#+title: init.el
#+property: header-args:emacs-lisp :tangle init.el :mkdirp yes
#+auto_tangle: t

パッケージ管理は use-package ではなく [[https://codeberg.org/pkal/setup.el][setup.el]] を使う。
このファイルは Nix (twist.nix) 側の =pkgs.tangleOrgBabelFile= で
=init.el= に tangle される。

* setup.el のブートストラップ

twist.nix がすでにすべてのパッケージを Nix store 上にビルド・配置して
いるので、setup.el 標準の =:package= (中身は本来 =package-install= を
呼ぶだけのもの) は何もしない no-op に置き換える。これが
「パッケージ管理は use-package ではなく setup.el」を twist.nix と
組み合わせるための要になる。

#+begin_src emacs-lisp
;; -*- lexical-binding: t; -*-

(eval-and-compile
  (require 'setup))

(setup-define :package
  (lambda (_order) nil)
  :documentation "no-op: パッケージのインストールは twist.nix が担当する。"
  :repeatable t
  :shorthand #'cadr)
#+end_src

setup.el 自体が読み込まれた後は =setup= マクロで以下のように書ける。

#+begin_example emacs-lisp
;; ビルトイン機能の設定 (:package は不要)
(setup savehist
  (:require savehist)
  (savehist-mode 1))

;; 外部パッケージの設定
;; (:package foo) と書くだけで、tangle 時に foo が検出されて
;; nix/registries.nix 経由でロック・ビルドされる。
(setup (:package which-key)
  (:require which-key)
  (which-key-mode 1))
#+end_example

* Customize の保存先を変更する

twist.nix が作る =user-emacs-directory= は Nix store 上の読み取り専用
ディレクトリなので、=M-x customize= の保存先はデフォルトのままだと
書き込みに失敗する。書き込み可能な場所に変更しておく。

#+begin_src emacs-lisp
(setq custom-file
      (expand-file-name "custom.el"
                         (or (getenv "XDG_CONFIG_HOME") "~/.config/emacs-custom/")))
(make-directory (file-name-directory custom-file) t)
(when (file-exists-p custom-file)
  (load custom-file))
#+end_src

バックアップ・自動保存・ロックファイルも同様に、書き込み可能な場所に
まとめておく。

#+begin_src emacs-lisp
(let ((var-dir (expand-file-name "emacs/"
                                  (or (getenv "XDG_CACHE_HOME") "~/.cache/"))))
  (make-directory var-dir t)
  (setq backup-directory-alist `((".*" . ,var-dir))
        auto-save-file-name-transforms `((".*" ,var-dir t))
        lock-file-name-transforms `((".*" ,var-dir t))))
#+end_src

* 基本設定 (ビルトイン機能のみ)

#+begin_src emacs-lisp
(setq-default indent-tabs-mode nil
              tab-width 4)

(setq inhibit-startup-screen t
      initial-scratch-message nil
      ring-bell-function #'ignore
      use-short-answers t)

(column-number-mode 1)
(global-display-line-numbers-mode 1)

(keymap-global-set "C-x C-b" #'ibuffer)
#+end_src

最近使ったファイルの一覧、ミニバッファの履歴、カーソル位置を覚えて
おく。 いずれも Emacs 本体にビルトインの機能なので =:package= は不要。

#+begin_src emacs-lisp
(setup recentf
  (:require recentf)
  (recentf-mode 1))

(setup savehist
  (:require savehist)
  (savehist-mode 1))

(setup saveplace
  (:require saveplace)
  (save-place-mode 1))
#+end_src

文章向けのモードでは =visual-line-mode= を有効にする。 =:hook= を使うと
=(setup FEATURE ...)= の FEATURE から対応するフック
(ここでは =text-mode-hook=) を自動で推測してくれる。

#+begin_src emacs-lisp
(setup text-mode
  (:hook visual-line-mode))
#+end_src

* 外部パッケージの例

ここではパッケージ管理の配線を確認するための最小限の例として、
=which-key= だけを有効にしておく。 =(setup (:package NAME) ...)= と
書くだけで、この init.org を tangle したときに NAME が自動的に検出され、
Nix 側 (nix/registries.nix) でロック・ビルドされる。

#+begin_src emacs-lisp
(setup (:package which-key)
  (:require which-key)
  (which-key-mode 1))
#+end_src

新しいパッケージを追加したくなったら、この見出しの下に
=(setup (:package foo) ...)= を増やしていけばよい。 MELPA / GNU ELPA /
NonGNU ELPA / Emacsmirror のいずれにもないパッケージだけ、
=recipes/= 以下に MELPA 形式のレシピを追加する必要がある
(recipes/README.md 参照)。

パッケージを追加・変更したら、ロックファイルの更新を忘れずに:

#+begin_example sh
nix run .#lock
#+end_example
